name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        cache: gradle
        distribution: 'temurin'

    - name: Set up Gradle wrapper
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --no-daemon
